### ISSUE TITLE
GUI, highlight syntax, Dark theme, linux

### ISSUE THREAD

**Issue by knight2013** [BaseXdb/basex#1746] opened 2019-11-07 06:10 UTC
KDE NEON 5.1 (Ubuntu based)
Standart dark theme Breeze
BaseX version 9.2.4 highlight syntax is wrong.

![img-2019-11-07-10-13-00](https://user-images.githubusercontent.com/4256859/68364380-37481c80-0147-11ea-8c80-98691bcba017.png)

BaseX older version 8.5.1 highlight syntax is good.
![img-2019-11-07-10-09-11](https://user-images.githubusercontent.com/4256859/68364232-c30d7900-0146-11ea-93ba-b7ee6ac1d6d7.png)

Please ckeck BaseX version 9.2.4 for error.

**Comment by ChristianGruen** [comment] 2019-11-11 12:13
The Java color configuration might be handled inconsistently in KDE NEON. Could you please forward us the output of the following Java code?

```java
import javax.swing.*;

public class GUIColors {
  public static void main(final String... args) {
    System.out.println("JTextPane: " + Integer.toHexString(new JTextPane().getBackground().getRGB()));
    System.out.println("JTextField: " + Integer.toHexString(new JTextField().getBackground().getRGB()));
    System.out.println("JLabel: " + Integer.toHexString(new JLabel().getBackground().getRGB()));

    UIDefaults defaults = UIManager.getDefaults();
    System.out.println("TextPane.background: " + defaults.getColor("TextPane.background"));
    System.out.println("All: " + defaults);
  }
}
```

**Comment by knight2013** [comment] 2019-11-11 12:31
Result after run script
[guicolor.txt](https://github.com/BaseXdb/basex/files/3831286/guicolor.txt)

**Comment by ChristianGruen** [comment] 2019-11-11 12:49
Thanks. I noticed that your output contains light colors. I assume this is because the system’s Look and Feel needs to be applied. Could you have another go?

```java
import javax.swing.*;

public class GUIColors {
  public static void main(final String... args) throws Exception {
    UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
    UIDefaults defaults = UIManager.getDefaults();

    System.out.println("Backgrounds:");
    System.out.println("JTextPane: " + new JTextPane().getBackground());
    System.out.println("JTextField: " + new JTextField().getBackground());
    System.out.println("TextPane.background: " + defaults.getColor("TextPane.background"));

    System.out.println("\nForegrounds:");
    System.out.println("JTextPane: " + new JTextPane().getForeground());
    System.out.println("JTextField: " + new JTextField().getForeground());
    System.out.println("TextPane.foreground: " + defaults.getColor("TextPane.foreground"));

    System.out.println("\nUIManager:");
    System.out.println("All: " + defaults);
  }
}
```

I found the commit that changed the behavior (https://github.com/BaseXdb/basex/commit/e68056bf8c854d942f0095e0dadde384be730621#diff-7a794886c27e87ee22d41f848ab37e33R183). It was pushed because we had issues with other Linux window managers in the past.

**Comment by knight2013** [comment] 2019-11-11 13:01
Result of second script.
[guicolor.txt](https://github.com/BaseXdb/basex/files/3831400/guicolor.txt)

**Comment by ChristianGruen** [comment] 2019-11-11 13:51
Hm, I’m confused; the color codes in your result file are all white.

I tried to reproduce your environment:
* I set up a test instance of KDE neon (https://files.kde.org/neon/images/user/20191107-1116/neon-user-20191107-1116.iso),
* I enabled the dark theme,
* I installed Java via `sudo apt install default-jre`, and
* I launched the latest stable snapshot (http://files.basex.org/releases/latest/).

The background is white, too, as is the rest of the window:

![neon](https://user-images.githubusercontent.com/196589/68592010-5ff74b80-0492-11ea-937c-5edae804e462.png)

**Comment by ChristianGruen** [comment] 2019-11-12 08:54
@knight2013 Do you have an idea how we can reproduce your setup? Are additional settings required after the installation of KDE neon?

**Comment by knight2013** [comment] 2019-11-12 09:04
Settings my theme in KDE and current BaseX preferences
![theme-options](https://user-images.githubusercontent.com/4256859/68657303-e07a8280-054c-11ea-927b-0070e8427c8b.png)

**Comment by ChristianGruen** [comment] 2019-11-14 17:25
I have switched to the GTK look and feel, but the colors are the same:

![image](https://user-images.githubusercontent.com/196589/68880625-e1a5de00-070b-11ea-8b12-81fb5d834483.png)

Which version of Java are you using? What else could we try?

**Comment by knight2013** [comment] 2019-11-15 05:56
dark theme setup in GTK theme options  also:
http://i.imgur.com/DVbWt48.png

java version "1.8.0_201"

**Comment by ChristianGruen** [comment] 2019-11-16 08:19
I have switched to the dark themes in the GTK setup. BaseX 8.5.1 now looks a bit weird on my system:

![BaseX851](https://user-images.githubusercontent.com/196589/68990220-0061bd00-0851-11ea-89ab-10f9b503742c.png)

I guess this is due to the varying Java version we use (on my system, `java -version` yields `openjdk version "11.0.4"`). Would you mind checking out the latest version of Java that’s available for your system? If your BaseX GUI looks different to mine even with Java 11, 13 oder 14, there must be some more differences between your environment and my Vanilla setup that we would need to find.

I have uploaded a new snapshot of the latest version with revised color handling, feel free to test it:
http://files.basex.org/releases/latest/.

I am not sure, however, if we should keep that version, as we cannot tell what will change in newer versions of Java. I would still hope that BaseX on your system will be rendered better with a future version of Java.

**Comment by ChristianGruen** [comment] 2019-11-19 12:05
Do you think we have a chance to get your setup reproduced? Did you try the snapshot?

**Comment by knight2013** [comment] 2019-11-19 13:34
I am install old version from ubnuntu repository
$ sudo apt-get install basex
and make copy $ cp ~/Downloads/BaseX924.jar /basex.jar
I have normal GUI  in dark style now
![screenshot](https://user-images.githubusercontent.com/4256859/69150807-d6c7c080-0af2-11ea-8d2a-9439ad515ee8.png)

**Comment by ChristianGruen** [comment] 2019-11-20 08:57
I uninstalled jdk 11 and switched to jdk 8… same result. What does `apt list --installed | grep jre` output on your system?

**Comment by knight2013** [comment] 2019-11-20 09:30
I try install jdk 8 and jdk 11. Result as is on first comment.

$default-jre/bionic-upt list --installed | grep jre

pdates,bionic-security,now 2:1.11-68ubuntu1~18.04.1 amd64 [installed]
default-jre-headless/bionic-updates,bionic-security,now 2:1.11-68ubuntu1~18.04.1 amd64 [installed,automatic]
openjdk-11-jre/bionic-updates,bionic-security,now 11.0.4+11-1ubuntu2~18.04.3 amd64 [installed,automatic]
openjdk-11-jre-headless/bionic-updates,bionic-security,now 11.0.4+11-1ubuntu2~18.04.3 amd64 [installed,automatic]
openjdk-8-jre-headless/bionic-updates,bionic-security,now 8u222-b10-1ubuntu1~18.04.1 amd64 [installed]

**Comment by ChristianGruen** [comment] 2019-11-26 09:01
So it seems we cannot adjust the settings of our systems 100%.
Could you post a screenshot of the latest snapshot (http://files.basex.org/releases/latest/)?

**Comment by knight2013** [comment] 2019-11-26 09:57
I am set force dark theme for all java applications
$nano ~/.profile
$export _JAVA_OPTIONS='-Dawt.useSystemAAFontSettings=on -Dswing.aatext=true -Dswing.defaultlaf=com.sun.java.swing.plaf.gtk.GTKL$

And setup last release 9.3 Beta. 
http://i.imgur.com/QQfFH1O.png

Good, but syntax  darker little...

**Comment by ChristianGruen** [comment] 2019-11-26 10:25
Your Java options are detected correctly...

```
$ java -jar BaseX851.jar 
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true -Dswing.defaultlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel -Dswing.crossplatformlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel
```

...but the rendering doesn't change Do you have any other custom settings?

**Comment by ChristianGruen** [comment] 2019-11-29 04:05
I am closing this. I will keep the latest changes in the current code base, and it will be part of BaseX 9.3. If users experience problems, we might revert the changes.

**Closed by ChristianGruen** 2019-11-29 04:05 UTC
