### ISSUE TITLE
Possible NPE in DiskData::write

### ISSUE THREAD

**Issue by brandes-pq** [BaseXdb/basex#2086] opened 2022-04-06 15:19 UTC
### Description of the Problem

After moving several documents from one database to another and a consequent call to `db:optimize` inside a RESTXQ method, sometimes a NullPointerException is thrown, resulting in a HTTP status code of 500. 

The corresponding log entry is:

```
data/.logs/2022-03-14.log:10:07:18.737	172.18.0.5:52900	admin	500	Unexpected error: Improper use? Potential bug? Your feedback is welcome: Contact: basex-talk@mailman.uni-konstanz.de Version: BaseX 9.5.1 Java: Temurin, 1.8.0_322 OS: Linux, amd64 Stack Trace: java.lang.NullPointerException 
at org.basex.data.DiskData.write(DiskData.java:151) at org.basex.data.DiskData.close(DiskData.java:160) 
at org.basex.core.Datas.unpin(Datas.java:52) at org.basex.core.cmd.Close.close(Close.java:45) 
at org.basex.core.cmd.OptimizeAll.optimizeAll(OptimizeAll.java:126) 
at org.basex.query.up.primitives.db.DBOptimize.apply(DBOptimize.java:120) 
at org.basex.query.up.DataUpdates.apply(DataUpdates.java:169) 
at org.basex.query.up.ContextModifier.apply(ContextModifier.java:120) 
at org.basex.query.up.Updates.apply(Updates.java:172) at org.basex.query.QueryContext.update(QueryContext.java:702) 
at org.basex.query.QueryContext.iter(QueryContext.java:331) 
at org.basex.http.restxq.RestXqResponse.serialize(RestXqResponse.java:76) 
at org.basex.http.web.WebResponse.create(WebResponse.j...	112.56 ms
```

Unfortunately, this is not always reproducible and tends to only occur when processing large batches of data. I cannot disclose the original data set, but I am working on generating data that can reproduce the bug.

The code for moving documents between databases looks like this: 

```xquery
    db:replace($trg-db, $path, db:open($src-db, $path)),
    db:delete($src-db, $path)
```

The call to `optimize` looks like this:

```xquery
(for $db in $some-dbs where not(db:property($db, 'uptodate')) return $db)
! db:optimize(., true(), map {
    'updindex': true(),
    'textindex': true(),
    'attrindex': true(),
    'tokenindex': false(),
    'ftindex': false()
})
```

### Expected Behavior

No exception should be thrown, the databases should be successfully optimized after the query.

### Steps to Reproduce the Behavior

As described above, this happens very sporadically. We are working on reproducing the problem reliably.

### What is your configuration?

* Custom-built basex docker container, BaseX version 9.5.1
* Max heap size 4GB
* Java: Temurin, 1.8.0_322 
* OS: Linux, amd64

**Comment by ChristianGruen** [comment] 2022-04-08 12:07
A tough one. Some technical remarks/notes to myself:

* [idmap](https://github.com/BaseXdb/basex/blob/master/basex-core/src/main/java/org/basex/data/DiskData.java#L151) (the data structure that maps static node id values to their implicit pre values) seems to be `null` although it should always be assigned if `meta.updindex` is true.
* There’s only one place in the code where the [variable is reassigned](https://github.com/BaseXdb/basex/blob/master/basex-core/src/main/java/org/basex/core/cmd/Optimize.java#L198) (but the functions are never concurrently accessed).
* Presumably, `meta.updindex` [is enabled](https://github.com/BaseXdb/basex/blob/master/basex-core/src/main/java/org/basex/query/up/primitives/db/DBOptimize.java#L104) without `idmap` being instantiated; but we’ll then need to find out why it doesn’t consistently fail.

Can you tell if `updindex` was enabled in all the original databases before they were optimized?

Data for reproducing the issue is welcome; I can well imagine it’s hard to generate it.

**Comment by ChristianGruen** [comment] 2022-04-24 12:17
Have you encountered this bug repeatedly, or could it also have been caused by parallel access to the database instances by another instance of BaseX?

**Comment by ChristianGruen** [comment] 2022-05-21 18:07
Dropping this one for now. Feel free to reopen it if you have new hints on how to reproduce this.

**Closed by ChristianGruen** 2022-05-21 18:07 UTC
Labels: bug
