### ISSUE TITLE
WebDAV server creating collections for simple text content

### ISSUE THREAD

**Issue by zopyx** [BaseXdb/basex#1450] opened 2017-04-11 17:33 UTC
BaseX 8.6.3 - any platform.

I connect with cadaver to a fresh BaseX installation

```
cadaver http://localhost:8984/webdav
```

I create a new file using "edit foo.txt" from within the cadaver shell.

After saving there is only a collection "foo".

```
dav:/webdav/> ls
Listing collection `/webdav/': succeeded.
Coll:   foo                                    0  Apr 11 19:29

```

```
[qtp1456208737-20] INFO com.bradmcevoy.http.webdav.WebDavProtocol - resourceTypeHelper: class com.bradmcevoy.http.webdav.WebDavResourceTypeHelper
[qtp1456208737-20] INFO com.bradmcevoy.http.webdav.WebDavProtocol - quotaDataAccessor: class com.bradmcevoy.http.quota.DefaultQuotaDataAccessor
[qtp1456208737-20] INFO com.bradmcevoy.http.webdav.WebDavProtocol - creating default patcheSetter: class com.bradmcevoy.http.webdav.PropertySourcePatchSetter
[qtp1456208737-20] INFO com.bradmcevoy.http.HttpManager - OPTIONS :: http://localhost:8984/webdav/ - http://localhost:8984/webdav/
[qtp1456208737-18] INFO com.bradmcevoy.http.HttpManager - PROPFIND :: http://localhost:8984/webdav/ - http://localhost:8984/webdav/
[qtp1456208737-22] INFO com.bradmcevoy.http.HttpManager - PROPFIND :: http://localhost:8984/webdav/ - http://localhost:8984/webdav/
[qtp1456208737-18] INFO com.bradmcevoy.http.HttpManager - PROPFIND :: http://localhost:8984/webdav/foo.txt - http://localhost:8984/webdav/foo.txt
[qtp1456208737-19] INFO com.bradmcevoy.http.HttpManager - OPTIONS :: http://localhost:8984/webdav/foo.txt - http://localhost:8984/webdav/foo.txt
[qtp1456208737-22] INFO com.bradmcevoy.http.HttpManager - PROPFIND :: http://localhost:8984/webdav/foo.txt - http://localhost:8984/webdav/foo.txt
[qtp1456208737-20] INFO com.bradmcevoy.http.HttpManager - GET :: http://localhost:8984/webdav/foo.txt - http://localhost:8984/webdav/foo.txt
[qtp1456208737-20] INFO com.bradmcevoy.http.HttpManager - PUT :: http://localhost:8984/webdav/foo.txt - http://localhost:8984/webdav/foo.txt
[qtp1456208737-20] WARN com.bradmcevoy.http.http11.PutHandler - Your resource factory returned a resource with a different name to that requested!!! Requested: webdav returned:  - resource factory: class org.basex.http.webdav.WebDAVFactory
[qtp1456208737-20] INFO com.bradmcevoy.http.HttpManager - PROPFIND :: http://localhost:8984/webdav/foo.txt - http://localhost:8984/webdav/foo.txt
[qtp1456208737-20] INFO com.bradmcevoy.http.HttpManager - PROPFIND :: http://localhost:8984/webdav/-la/ - http://localhost:8984/webdav/-la/
[qtp1456208737-22] INFO com.bradmcevoy.http.HttpManager - PROPFIND :: http://localhost:8984/webdav/ - http://localhost:8984/webdav/

```

**Comment by zopyx** [comment] 2017-04-11 18:36
It appears to be by design that you can have collections only inside the root folder but not single files.

**Comment by micheee** [comment] 2017-04-12 08:26
Hi @zopyx, 

yes this is [by design](http://docs.basex.org/wiki/WebDAV).

> In the WebDAV root directory, all existing databases are listed. As new resources can only be stored inside a database, it is not possible to store files in the root directory. If a file is copied on top level, a new database will be created, which contains this resource.

You may circumvent this by explicitly adressing a single database, i.e. `/webdav/myFolder` as your root.

**Comment by ChristianGruen** [comment] 2017-04-18 10:16
I can only agree with @micheee’s comment. @zopyx: I’ve closed this issue; feel free to reopen it if you there’s some more need for discussion.

**Closed by ChristianGruen** 2017-04-18 10:16 UTC
