### ISSUE TITLE
db:optimize("..",fn:true()) can corrupt database

### ISSUE THREAD

**Issue by apb2006** [BaseXdb/basex#702] opened 2013-05-17 16:32 UTC
I have a database
(zip file here https://docs.google.com/file/d/0B_HWsgek7hAeQTdKY1lpMXh2WDQ/edit?usp=sharing  3mb zip, 73mb unzip)
After running `db:optimize("pics",fn:true())` in the GUI `inspect`  reports:
````
Checking main table (4038420 nodes):
- 0 invalid node kinds
- 0 invalid parent references
- 423795 wrong parent/descendant relationships (pre: 2048,..)
Warning: Database is inconsistent.
````
db:system() is 
````
<system>
  <generalinformation>
    <version>7.7 beta</version>
    <usedmemory>12161 KB</usedmemory>
  </generalinformation>
  <mainoptions>
    <dbpath>C:\Program Files\BaseX\data</dbpath>
    <debug>false</debug>
    <eventport>1985</eventport>
    <globallock>false</globallock>
    <host>localhost</host>
    <httplocal>false</httplocal>
    <keepalive>600</keepalive>
    <lang>English</lang>
    <langkeys>false</langkeys>
    <log>true</log>
    <logmsgmaxlen>1000</logmsgmaxlen>
    <nonproxyhosts>*.reuters.com</nonproxyhosts>
    <parallel>8</parallel>
    <password/>
    <port>1984</port>
    <proxyhost>10.1.51.10</proxyhost>
    <proxyport>80</proxyport>
    <repopath>C:\Program Files\BaseX\repo</repopath>
    <restxqpath>restxq</restxqpath>
    <serverhost/>
    <serverport>1984</serverport>
    <stopport>8985</stopport>
    <timeout>30</timeout>
    <user/>
    <webpath>C:\Program Files\BaseX\webapp</webpath>
  </mainoptions>
  <options>
    <addarchives>true</addarchives>
    <addcache>false</addcache>
    <addraw>false</addraw>
    <attrindex>true</attrindex>
    <autoflush>true</autoflush>
    <bindings/>
    <cachequery>true</cachequery>
    <casesens>false</casesens>
    <catfile/>
    <chop>true</chop>
    <compplan>true</compplan>
    <createfilter>*.xml</createfilter>
    <createonly>false</createonly>
    <diacritics>false</diacritics>
    <dotcompact>false</dotcompact>
    <dotdisplay>true</dotdisplay>
    <dotplan>false</dotplan>
    <dotty>dotty</dotty>
    <dtd>false</dtd>
    <exporter/>
    <forcecreate>false</forcecreate>
    <ftindex>false</ftindex>
    <ftindexsplitsize>0</ftindexsplitsize>
    <htmlopt>html=false,omit-xml-declaration=false,method=xml,nons=false,nobogons=false,nodefaults=false,nocolons=false,norestart=false,ignorable=false,emptybogons=false,any=false,norootbogons=false,nocdata=false,lexical=false,encoding=utf-8</htmlopt>
    <indexsplitsize>0</indexsplitsize>
    <inlinelimit>0</inlinelimit>
    <intparse>true</intparse>
    <language>English</language>
    <lserror>0</lserror>
    <mainmem>false</mainmem>
    <maxcats>100</maxcats>
    <maxhits>250000</maxhits>
    <maxlen>96</maxlen>
    <maxstat>30</maxstat>
    <parser>xml</parser>
    <parseropt>encoding=UTF-8,flat=false,format=verbose,header=false,json_spec=RFC4627,json_unesc=true,jsonml=false,lines=true,separator=comma</parseropt>
    <queryinfo>true</queryinfo>
    <querypath>C:/Documents and Settings/andrew.bunce/Desktop/file2</querypath>
    <runs>1</runs>
    <serialize>true</serialize>
    <serializer/>
    <skipcorrupt>false</skipcorrupt>
    <stemming>false</stemming>
    <stopwords/>
    <stripns>false</stripns>
    <tailcalls>42</tailcalls>
    <textindex>true</textindex>
    <updindex>false</updindex>
    <writeback>false</writeback>
    <xmlplan>true</xmlplan>
    <xquery3>true</xquery3>
  </options>
</system>
````

**Comment by mingarao** [comment] 2016-04-20 09:39
Bug when selecting "Full optimization" in the dba module : 
![basex-optimize-bug](https://cloud.githubusercontent.com/assets/6703169/14670214/746c13f4-06ec-11e6-883c-1c35dd35bf0c.png)
Answer : 
```
HTTP ERROR 500

Problem accessing /dba/optimize. Reason:

    Unexpected error: Improper use? Potential bug? Your feedback is welcome:
Contact: basex-talk@mailman.uni-konstanz.de
Version: BaseX 8.4.1
Java: Oracle Corporation, 1.8.0_66
OS: Linux, amd64
Stack Trace: 
java.lang.RuntimeException: bvm: lock file does not exist.
	at org.basex.util.Util.notExpected(Util.java:61)
	at org.basex.data.DiskData.finishUpdate(DiskData.java:231)
	at org.basex.query.up.ContextModifier.apply(ContextModifier.java:139)
	at org.basex.query.up.Updates.apply(Updates.java:153)
	at org.basex.query.QueryContext.iter(QueryContext.java:359)
	at org.basex.http.restxq.RestXqResponse.create(RestXqResponse.java:56)
	at org.basex.http.restxq.RestXqModule.process(RestXqModule.java:101)
	at org.basex.http.restxq.RestXqFunction.process(RestXqFunction.java:107)
	at org.basex.http.restxq.RestXqServlet.run(RestXqServlet.java:44)
	at org.basex.http.BaseXServlet.service(BaseXServlet.java:64)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:684)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:503)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:557)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:429)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
	at org.eclipse.jetty.server.Server.handle(Server.java:370)
	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:494)
	at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:982)
	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:1043)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:861)
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:236)
	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:696)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:53)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
	at java.lang.Thread.run(Thread.java:745)

Powered by Jetty://

```

By unchecking "Full optimization", no error, everything works fine.

**Comment by ChristianGruen** [comment] 2016-04-20 11:53
Hm, we should definitely get this fixed. So far, unfortunately, I didn’t manage to get it reproduced. @mingarao: Does it happen every time you run it? If yes, it would be great if you could somehow provide me with the database!

**Comment by mingarao** [comment] 2016-04-20 12:14
Because of our showcase tomorrow in Roma, I am not trying too much to reproduce bugs today :)

I copied the DB and ran the full optimization on the copy, and no bug occured...

Note that we always have had a lot of problems accessing this DB via oXygen (WebDAV) with constant "502 Bad Gateway" errors. Don't know if it can be linked.

I send you the DB anyway.

**Comment by ChristianGruen** [comment] 2016-05-24 12:42
More feedback on this will be welcome! I’ll do my best to get it reproduced by myself, as it’s not the first that problems with the full optimization feature have been reported.

**Comment by mgaerber** [comment] 2016-07-12 12:14
I can reproduce the following:
* create DB 'test' (in DBA)  with Text, Attribute and Fulltext index (not incremental)
* Add document and optimize (not full)
* call   db:optimize('test', true(), map { 'ftindex': true() })
which then creates a DB backup and leaves the original DB in corrupt state

**Comment by ChristianGruen** [comment] 2016-07-12 12:37
@mgaerber: I really hoped I could now reproduce this… But I failed again, both with Linux and Windows. My questions back:

1. What OS did you use for testing?
2. Does it fail every time on your machine?
3. Does the following command script run through? You can save it as `commands.bxs` and launch it with `basex commands.bxs`; it should do exactly what DBA does:

```
xquery db:create('test', (), (), map { 'ftindex': true() })
xquery db:add('test', <x/>, 'x.xml')
xquery db:optimize('test')
xquery db:optimize('test', true(), map { 'ftindex': true() })
xquery db:list()
```

**Comment by ChristianGruen** [comment] 2016-07-12 12:42
Two more questions:

4. Do you have any other options assigned in the `web.xml` or `.basex` files? Auto optimize, Updindex, …
5. Which version of BaseX are you using?

**Comment by mgaerber** [comment] 2016-07-12 15:39
I am still trying to reproduce locally. 

Setup is on Windows 7/10 with basex 8.4.4

The two dbs that 'survived' did have the UPDINDEX option set. No Fulltext.
The db that is gone did not have UPDINDEX but was Fulltext

from .basex
...
GLOBALLOCK = false
...
PARALLEL = 8

**Comment by ChristianGruen** [comment] 2016-07-15 06:22
Everyone: Feedback on the [latest snapshot](http://files.basex.org/releases/latest/) is welcome. I couldn’t reproduce anything in our systems so far, but I rewrote the optimization workflow in the code, maybe that helps.

**Comment by ChristianGruen** [comment] 2016-07-19 17:07
Closing this (in the hope that there won’t be a need to reopen this…).

**Closed by ChristianGruen** 2016-07-19 17:07 UTC
Labels: bug
