### ISSUE TITLE
Out of Main Memory. when uploading json file via REST

### ISSUE THREAD

**Issue by derMart** [BaseXdb/basex#1173] opened 2015-07-14 15:46 UTC
Hello,

i'm using the BaseX824-20150714.130938 snapshot of BaseX trying to upload a json file of approx. 110mb size using the REST interface (server is started using basexhttp). I have increased the Xmx flags to 2g which helps not to kill the upload immediately but still i get the response: "Out of Main Memory." There is no exception thrown at the console output though.

**Comment by ChristianGruen** [comment] 2015-07-14 17:01
I think we should simply limit the upload size in Jetty to a smaller value to avoid any server-side out-of-memory errors. URL: https://wiki.eclipse.org/Jetty/Howto/Configure_Form_Size

**Comment by derMart** [comment] 2015-07-14 17:49
oh, well, so that means there is no way to upload files of that size using REST? That would be really bad...

**Comment by ChristianGruen** [comment] 2015-07-14 17:51
I see, I mixed this up; I had RESTXQ and DBA in mind. Well, REST allows you to stream data, but only if XML is uploaded. We would need to convert JSON in a streaming fashion. We haven't done so until now, because we didn't work with JSON files of that size so far.

Can you successfully create databases from that input with the BaseX GUI?

**Comment by derMart** [comment] 2015-07-15 10:59
No, the same problem appeared in the BaseX GUI. I had to increase java memory limit even more. It needed around 7gb memory during import, then it was working. Quite some overhead for 100mb...
Is it possible to lower this?

**Comment by ChristianGruen** [comment] 2015-07-15 11:05
Ok, so it's a basic conversion problem. Generally it should be possible, but it's surely not trivial, because we provide various JSON representations, and all of them would need to be rewritten in a streaming fashion.

As I guess that there are hardly any processors out there that can handle or convert such large JSON files (do you know any?), you could try to split your JSON document into smaller entities.

**Comment by ChristianGruen** [comment] 2015-07-15 11:06
PS: We prefer to have discussions like this on our basex-talk mailing list. Usually, we use the bug tracker for confirmed bugs or feature requests.

**Comment by derMart** [comment] 2015-07-20 13:31
Sorry about that. I saw https://github.com/BaseXdb/basex/issues/976, which is somehow related to this issue, that's why I was posting it on github. 
I did some further tests. Uploading and converting json -> xml in various formats (attributes, direct, basic) has large memory overhead. Downloading and converting back xml -> json however had very small memory footprint for all the formats. 
For my usecase I just need to retrieve the json file as a whole, so the work around for me is to store the file as raw json on the server.

**Comment by ChristianGruen** [comment] 2015-08-07 10:17
I'm closing this for now, because I believe the required changes to offer a generic solution for all the available JSON conversions would cost us too much time. – Have you already found an alternative solution for converting your JSON data to XML – or do you have any other system that is capable of processing the original file?

**Closed by ChristianGruen** 2015-08-07 10:17 UTC
Labels: feature
