### ISSUE TITLE
Python client bug

### ISSUE THREAD

**Issue by afedosenko** [BaseXdb/basex#1555] opened 2018-03-29 17:03 UTC
```
session = BaseXClient.Session('localhost', 1984, 'admin', 'admin')

session2 = BaseXClient.Session('localhost', 1984, 'admin', 'admin')
session2.execute("check database")

query = session.query("collection('database')")

for code, item in query.iter():
    //some item modification
    session2.replace("{}.xml".format(item_path), modified_item)
```
The execution of the script stops after the first iteration. How can I read and change data in a single cycle?

**Comment by ChristianGruen** [comment] 2018-03-31 12:13
It would be interesting to know what `item_path` and `modified_item` is. Could you please provide a complete code example? Next, does the problem also occur when using a single session?

**Comment by afedosenko** [comment] 2018-04-02 08:55
```
from BaseXClient import BaseXClient
from parsel import Selector

def main():
    session = BaseXClient.Session('localhost', 1984, 'admin', 'admin')

    session2 = BaseXClient.Session('localhost', 1984, 'admin', 'admin')
    session2.execute("check epo_recovered")

    query = session.query("collection('epo_recovered')")

    for code, item in query.iter():
        selector = Selector(text=item, type='xml')

        country = selector.xpath('@country').extract_first()
        doc_number = selector.xpath('@doc-number').extract_first()
        kind = selector.xpath('@kind').extract_first()

        key = '{}_{}_{}'.format(country, doc_number, kind)
        # WO_2018022284_A1 key example
        # each item have unique key

        session2.replace("{}.xml".format(key), item)
```

This is a very simplified example with the same problem.

**Comment by afedosenko** [comment] 2018-04-02 09:02
Exception raised when using a single session.

```
    session.replace("{}.xml".format(key), item)
  File "/usr/local/lib/python2.7/dist-packages/BaseXClient/BaseXClient.py", line 165, in replace
    self.__send_input(12, path, content)
  File "/usr/local/lib/python2.7/dist-packages/BaseXClient/BaseXClient.py", line 200, in __send_input
    raise IOError(self.info())
IOError: <exception str() failed>
```

**Comment by ChristianGruen** [comment] 2018-04-04 11:29
Thanks. I haven’t used the Python client by myself so far, but I’ll see what I can do. If you have some time left, I would be interested in knowing if the problem also occurs with other clients.

**Comment by ChristianGruen** [comment] 2018-04-11 07:53
As far as I can judge, the Python client does not cache the server results before returning them to the client. This is why side effects will occur when performing concurrent updates. I think I’ll need to pass on the issue to @hhsprings or @xokomola: Do you think the behavior can be aligned with the Java implementation?

**Comment by xokomola** [comment] 2018-04-11 12:31
Hi Christian,
I'm afraid my Python skills aren't up to this. This may be have been an issue with the python client all along.
I hope someone else with better Python skills can help.

**Comment by igneus** [comment] 2019-02-21 21:09
I thought I would try to dig in this issue, but wasn't able to reproduce it. Seems to work fine with both Python 2.7 and 3.6.
(Tried with BaseX server 9.0.1, as packaged in Ubuntu, Python client from the current master.)

Here is my attempt of a self-contained test example, data included. @afedosenko will it fail for you, too? Or did I miss some important factor like collection size, size of the XML documents, ...?

```python
import re
from BaseXClient import BaseXClient

## populate database with test data

session = BaseXClient.Session('localhost', 1984, 'admin', 'admin')
session.execute('drop database test_database')
session.execute('check test_database')

# populate with <a>
for i in range(0, 100):
    session.add('{}.xml'.format(i), '<a>{}</a>'.format(i))
    
session.close()

## try concurrent connections

session = BaseXClient.Session('localhost', 1984, 'admin', 'admin')

session2 = BaseXClient.Session('localhost', 1984, 'admin', 'admin')
session2.execute("check test_database")

query = session.query("collection('test_database')")

# change each <a> to <b>
for code, item in query.iter():
    i = int(re.search(r'(\d+)', item).group(0))
    
    print(item)
    new = '<b>{}</b>'.format(i)
    print(new)
    
    session2.replace("{}.xml".format(i), new)
```

**Comment by afedosenko** [comment] 2019-02-22 07:56
@igneus Does not work with a large collection size.

**Comment by igneus** [comment] 2019-02-22 13:16
Is it possible to say how large approximately?

I tried adding more records to the example posted above, changing 100 records to 100000, but apart of the extended execution time and moderate CPU usage, I didn't encounter any issues.

**Comment by afedosenko** [comment] 2019-02-22 13:59
@igneus Collections size is 11.49 GB and about 1.000.000 records

**Comment by afedosenko** [comment] 2019-02-28 08:48
@igneus Try next:

```python
import re
from BaseXClient import BaseXClient

## populate database with test data

session = BaseXClient.Session('localhost', 1984, 'admin', 'admin')
session.execute('drop database test_database')
session.execute('check test_database')

# populate with <a>
for i in range(1, 30000):
    session.add('{}.xml'.format(i), '<a key="{}">{}</a>'.format(i, str(i)*i))

session.close()

## try concurrent connections

session = BaseXClient.Session('localhost', 1984, 'admin', 'admin')

session2 = BaseXClient.Session('localhost', 1984, 'admin', 'admin')
session2.execute("check test_database")

query = session.query("collection('test_database')")

# change each <a> to <b>
for code, item in query.iter():
    key = re.search(r'(\d+)', item).group(0)

    print(item)
    new = '<b key="{}">{}</b>'.format(key, key)
    print(new)

    session2.replace("{}.xml".format(key), new)
```

**Comment by igneus** [comment] 2019-02-28 09:31
@afedosenko Great! 11 GB test database was too large a beast for me to create and work with, this is much better :)
I confirm that this last example reproduces the behaviour initially reported on both Python 2.7 and 3.6

```
$ python test.py 
<a key="1">1</a>
<b key="1">1</b>
```

and this is the traceback when killed because nothing more happens:

```
^CTraceback (most recent call last):
  File "test.py", line 33, in <module>
    session2.replace("{}.xml".format(key), new)
  File "/home/igneus/github_hacking/basex/basex-api/src/main/python/BaseXClient/BaseXClient.py", line 165, in replace
    self.__send_input(12, path, content)
  File "/home/igneus/github_hacking/basex/basex-api/src/main/python/BaseXClient/BaseXClient.py", line 198, in __send_input
    self.__info = self.recv_c_str()
  File "/home/igneus/github_hacking/basex/basex-api/src/main/python/BaseXClient/BaseXClient.py", line 189, in recv_c_str
    return self.__swrapper.recv_until_terminator()
  File "/home/igneus/github_hacking/basex/basex-api/src/main/python/BaseXClient/BaseXClient.py", line 72, in recv_until_terminator
    self.__fill_buffer()
  File "/home/igneus/github_hacking/basex/basex-api/src/main/python/BaseXClient/BaseXClient.py", line 55, in __fill_buffer
    self.__bsize = self.__s.recv_into(self.__buf)
KeyboardInterrupt
```

I can't promise I will find time to work on this in the near future, though.

**Comment by igneus** [comment] 2019-03-04 20:28
I further simplified the example, trying to remove all non-essential complexity and reduce size of the test database.

I'm not sure if the threshold of approximately 1700 records of the given size works universally to reproduce the issue, or if it's system- or configuration-dependent.

```python
import re
from BaseXClient import BaseXClient

RECORDS = 1700
RECORD_SIZE = 3000

def connect():
    return BaseXClient.Session('localhost', 1984, 'admin', 'admin')

## populate database with test data

session = connect()
session.execute('drop database test_database')
session.execute('check test_database')

for i in range(1, RECORDS):
    session.add('{}.xml'.format(i), '<a key="{}">{}</a>'.format(i, 'a' * RECORD_SIZE))

session.close()

## try concurrent connections

session = connect()

session2 = connect()
session2.execute("check test_database")

query = session.query("collection('test_database')")

for code, item in query.iter():
    print(item)
    key = re.search(r'(\d+)', item).group(0)

    session2.replace("{}.xml".format(key), '<b></b>')
```

**Comment by igneus** [comment] 2019-03-04 20:53
I suspected the other client implementations could also suffer from this issue, so I wrote [the same program also in Ruby and PHP](https://gist.github.com/igneus/61f7fbfdf87883a41a2647da2bc55472), but they work fine, regardless of the value of `RECORDS`.

**Comment by dominikk** [comment] 2020-08-06 10:29
Hi there @afedosenko,

we have updated our python client. Feel free to give it another go - and please let us know if you do so. We're always happy about feedback :+1:

**Comment by ChristianGruen** [comment] 2021-01-04 09:24
I’m closing the issue (I assume this has been fixed).

**Closed by ChristianGruen** 2021-01-04 09:24 UTC
Labels: bug
