### ISSUE TITLE
Wrong Xquery behaviour

### ISSUE THREAD

**Issue by VincentBiragnet** [BaseXdb/basex#1140] opened 2015-05-12 15:54 UTC
The query below does not output expected result:

```
declare namespace local = "local"; 

declare function local:test($nodes as node()*){
  let $numbers := (2,3)
  return for $n at $k in $numbers
         return $nodes/*[$numbers[$k]]          
};

local:test((<c><c0/><c1/></c>, <d><d0/><d1/><d2/></d>))
```

But it works with tiny modifications: 

* without function call

```
let $nodes := (<c><c0/><c1/></c>, <d><d0/><d1/><d2/></d>),
    $numbers := (2,3)
return for $n at $k in $numbers
       return $nodes/*[$numbers[$k]]
```

* when using `position()`:

```
declare namespace local = "local"; 

declare function local:test($nodes as node()*){
  let $numbers := (2,3)
  return for $n at $k in $numbers
         return $nodes/*[position() = $numbers[$k]]          
};

local:test((<c><c0/><c1/></c>, <d><d0/><d1/><d2/></d>))
```

**Comment by ChristianGruen** [comment] 2015-05-12 17:06
Confirmed… Slightly smaller example:

```xquery
declare function local:test() {
  for $n in (1, 1)
  return <_><correct/><wrong/></_>/*[$n[1]]
};
local:test()
```

**Comment by ChristianGruen** [comment] 2015-05-12 17:12
Related (shouldn't raise an error):

```xquery
for $n in (2,2)
return (<c><c0/></c>, <d><d0/><d2/></d>)/*[$n[$n]]
```

**Comment by LeoWoerteler** [comment] 2015-05-12 17:16
The problem seems to be that `IterPosStep#preds(ANode)` does not set `qc.pos` if the predicate is not statically known to be numeric. This is triggered in the original query because `BaseXItemAt` does not copy the inferred output type when it is copied for inlining.

**Comment by ChristianGruen** [comment] 2015-05-12 17:32
This sounds as if you already found the solution? ;) The second issue would probably be fixed by rewriting [StandardFunc:102](https://github.com/BaseXdb/basex/blob/master/basex-core/src/main/java/org/basex/query/func/StandardFunc.java#L102) to `copyType(sig.get(sc, info, arg));`..

**Comment by ChristianGruen** [comment] 2015-05-12 19:28
Fixed in the latest snapshot; thanks.

**Closed by ChristianGruen** 2015-05-12 19:28 UTC
