### ISSUE TITLE
Check Command NPE in BaseXGUI when a treemap view was open

### ISSUE THREAD

**Issue by micheee** [BaseXdb/basex#1207] opened 2015-10-22 06:49 UTC
### To reproduce:

1. Open existing database, Command: `open test`
2. Open treemap, Menu: `Visualization -> Map`
3. Check non-existing database, Command: `check test-non-existing`

### Result

```
Could not execute CHECK test-non-existing:
Improper use? Potential bug? Your feedback is welcome:
Contact: basex-talk@mailman.uni-konstanz.de
Version: BaseX 8.3
Java: Oracle Corporation, 1.8.0_25
OS: Mac OS X, x86_64
Stack Trace: 
java.lang.ArrayIndexOutOfBoundsException: 0
	at org.basex.gui.view.map.BinaryAlgo.calcMap(BinaryAlgo.java:39)
	at org.basex.gui.view.map.BinaryAlgo.calcMap(BinaryAlgo.java:12)
	at org.basex.gui.view.map.MapLayout.makeMap(MapLayout.java:112)
	at org.basex.gui.view.map.MapView.calc(MapView.java:287)
	at org.basex.gui.view.map.MapView.refreshLayout(MapView.java:156)
	at org.basex.gui.view.map.MapView.refreshInit(MapView.java:110)
	at org.basex.gui.view.ViewNotifier.init(ViewNotifier.java:81)
	at org.basex.gui.GUI.exec(GUI.java:506)
	at org.basex.gui.GUI.access$400(GUI.java:43)
	at org.basex.gui.GUI$7.run(GUI.java:412)
```

**Comment by ChristianGruen** [comment] 2015-10-22 07:22
Hm, can't reproduce it… Probably some concurrency issues? Does it always on your machine?

**Comment by ChristianGruen** [comment] 2015-10-23 11:30
I take the liberty of closing this. Feel free to reopen it if it bugs you again.

**Closed by ChristianGruen** 2015-10-23 11:30 UTC
