### ISSUE TITLE
RESTXQ: Trying to get a RESTXQ result from within another RESTXQ request with fn:doc dead locks BaseX

### ISSUE THREAD

**Issue by simar0at** [BaseXdb/basex#1466] opened 2017-06-23 12:24 UTC
Steps to reproduce
---------------------

If I use fn:doc() to get another result from the server while generating some REST result I lock up BaseX.

Expected Behavoir
---------------------

1. I think requesting REST data from itself should work.
1. BaseX should at least throw an error if someone tries this.
1. I stumbled upon this when trying this using fn:doc with another RESTXQ endpoint in a saxon XSLT transform called from RESTXQ. I also think this should work.

Workaround
--------------

This works using http:send-request.

Sample Code
---------------

I use this code to reproduce:
```xquery
xquery version "3.1";
module namespace api = "http://acdh.oeaw.ac.at/xslt-call/api";

import module namespace rest = "http://exquery.org/ns/restxq";

(:declare %private function api:test-fetch-http() {
    serialize(http:send-request(<http:request method='get'/>, "http://localhost:8984/restxq-call?get-data=true")[2])
};:)

declare %private function api:test-fetch-http() {
    serialize(doc("http://localhost:8984/restxq-call?get-data=true"))
};

declare
  %rest:path("restxq-call")
  %rest:query-param("get-data", "{$get-data}", "false")
function api:index-file($get-data as xs:boolean) as item()+ {
  (
  <rest:response>
    <http:response status="200" message="">
      <http:header name="Content-Language" value="en"/>
      <http:header name="Content-Type" value="text/html; charset=utf-8"/>
    </http:response>
  </rest:response>,
  if ($get-data) then
  <test>
    <data>Sth</data>
  </test>
  else
  <html xmlns="http://www.w3.org/1999/xhtml">
    <title>Test</title>
    <body>        
       <h1>Test</h1>
       <p>Data: <br/>{ api:test-fetch-http() }</p>
    </body>
  </html>
  )
};
```

**Comment by ChristianGruen** [comment] 2017-06-23 12:33
Hi @simar0at, that’s true, a BaseX instance should never be called from the very same instance (see the documentation in http://docs.basex.org/wiki/Client_Module for a related problem). In the given case, you can simply call your RESTXQ function directly via `api:index-file(true())`.

For general questions on BaseX, and unconfirmed bug reports, please refer to our [basex-talk mailing list](http://basex.org/open-source/).

**Comment by simar0at** [comment] 2017-06-24 14:56
Boy you are fast to close the obviously irrelevant bug reports.

Oh silly me! Thanks for the enlightenment. Why didn't I just RTFM _about the Client Module_. RESTXQ endpoint**s**, Client Module, REST interface or xslt transform. That's all the same stuff. Why didn't I see that ... ? Is there actually any software out there on the internet where calling back using http protocol opens up a new instance? _Like the http Module for example?_

Speaking of which: _How does the http Module do the trick? Is it magic?_

I hoped you at least **consider giving the users an error** _instead of just teaching by dead lock_.
Further more I hope you **consider putting that lock up warning next to the RESTXQ Module** too.
Let's sum it up for the other script kiddies out there, shall we? D o  n o t  u s e fn:doc('http://localhost:8984/...')! Nowhere in your XQuery, nowhere in anything called by your XQuery especially XSL transfoms. You lock up the whole thing and that is by design.

We planned to use a BaseX instance shared for different projects. But if any rookie can dead lock the whole instance with several projects we might need to reconsider.

I did spend some time to find out other ways to do what I need using the fn:doc function.
So let me sum up what is obviously the same situation as described in the docs for the Client Module:
* Calling localhost in **any** way using BaseXes fn:doc. That includes:
  * Other RESTXQ endpoints (probably because they are not different invocations except when using the http Module). Some may think this is a workaround if you have a hard time phrasing your query for the updateing mode. Dead lock.
  * Calling to the REST interfaces run method. Dead lock. I did not try this using the http Module but I would not be surprised if it works.
* Having the silly idea of calling back into XQuery code from within the saxon XSL processor (I did not try the other one) using its fn:doc. Dead lock.

And thanks for enlighten me that I can call the function directly. Who would have guessed that? Did it ever occur to you that I might not have intended you to hunt down the phenomenon in my 500 lines of XQuery code? Yes, that was a **simplified** example.
But don't be alarmed. I'll let the grown ups do the work and and stop reporting **dead locks**. Seems you have to live with these nowadays. I go and ask politely at the kids table aka basex-talk if my XQuery style is to the liking of the geniuses that brought us BaseX. Sorry to have bothered you sir. Don't forget to delete this comment!

**Comment by ChristianGruen** [comment] 2017-06-25 07:34
Sorry for closing your comment, and sorry for making you feel bad and attack you emotionally; this was not my intent. I tried to give you a quick answer, and the result proved to be too offensive (I guess it would have been less offensive not to answer at all).

We use GitHub for documenting confirmed bugs and feature request, and our (...why do you call it kids table? it's much older than our github repository...) mailing list is used for discussing potential extensions. I see that this conflicts with the way you prefer to tackle issues, because it may be too old-school, so I have reopened this issue (we may need to improve our documentation in this regard), and I will try to give you a more elaborate response.

In the meanwhile, I would be glad if you could consider that BaseX is an open source project, not funded by any big organization that pays a big support team. We are no geniuses or heroes, we are just a small team of developers with limited resources, and we need to organize our work as effectively as possible. We appreciate if people contribute to our project (the history of our mailing list should demonstrate that to you).

**Comment by ChristianGruen** [comment] 2017-06-25 16:50
To lead this to a positive end, I have decided to reorganize my weekend, and I managed to find two tweaks that could solve part of your problem. The technical backgrounds:

* `fn:doc`, `fn:doc-available`, `fn:collection` and `fn:uri-collection` won’t be statically pre-evaluated anymore by the compiler if a URI is specified as input argument (this primarily led to the deadlock situation you encountered). Pre-evaluation is still enabled for non-URI arguments, because the functions can also be used to access databases, and pre-evaluation is required to trigger subsequent optimizations (such as descendant-step → child-step rewritings, physical index access estimations, etc.).
* Lock detection was improved for the same set of functions, and a global read lock will only be set if the input argument is no URI.

If `localhost` is recursively called, it is still possible to encounter deadlocks:

1. If too many repeated recursive calls are used, the maximum number of allowed transactions must be increased (see the [PARALLEL](http://docs.basex.org/wiki/Options#PARALLEL) option).
2. An updating query may trigger a global write lock. Subsequent transactions that are started by this query will be put on the transaction queue, but never evaluated because the initial query is still waiting for the result.
3. Obviously, it it always dangerous if a query produces cycles (example: a RESTXQ function is calling Saxon, Saxon is calling the same RESTXQ function with the same arguments, etc.). I think it is difficult to detect such cycles, and raise errors to interrupt them, but I will be happy to receive instructions how to tackle such cases.
4. Last but not least, I have observed that recursive calls to `localhost` will already be blocked by the web server (or if `HttpURLConnection.getInputStream()` is called). This may be because the very same client tries to trigger a new request while it’s still receiving an input stream. It’s just a guess; I think we first would need to reproduce this pattern outside BaseX to get a better clue on what’s going on.

I guess that most of the quoted items are non-issues in your setup; but I decided to at least name them here to complete the picture.

Omar, thanks for spending so much time in creating a reproducible example. This is surely something that is missing in many other error reports we get; I appreciate that. And once again, I apologize for the bad feelings caused by my reply (which should demonstrate well enough that you are talking to ordinary and mediocre human beings, not to geniuses). A new [stable snapshot](http://files.basex.org/releases/latest/) is available. Please give us some feedback if it works out for you.

**Comment by simar0at** [comment] 2017-06-26 08:59
Thank you for your time! I sincerely think that the BaseX developers are very good at what they are doing. Most of the time I am impressed what you can do with BaseX and at what speed. I just seem to have hit a corner case which admittedly is not obvious. I'll try it out and give you feedback. Keep up the good work! If you like I happyly delete my comment above.

**Comment by ChristianGruen** [comment] 2017-06-26 09:00
Thanks as well for the response! I hope my fix will do what it’s supposed to do.

**Comment by simar0at** [comment] 2017-06-26 10:58
Yes for me this short test works so I'm pretty sure the fix does what it should. I just tested what I was trying in the first place.
```xquery
xquery version "3.1";
module namespace api = "http://acdh.oeaw.ac.at/xslt-call/api";

import module namespace rest = "http://exquery.org/ns/restxq";
import module namespace xslt ="http://basex.org/modules/xslt";

declare
  %rest:path("")
  %rest:query-param("get-data", "{$get-data}", "false")
function api:index-file($get-data as xs:boolean) as item()+ {
  (
  <rest:response>
    <http:response status="200" message="">
      <http:header name="Content-Language" value="en"/>
      <http:header name="Content-Type" value="text/html; charset=utf-8"/>
    </http:response>
  </rest:response>,
  if ($get-data) then
  <test>
    <data>Sth</data>
  </test>
  else
  xslt:transform(<ignored/> , doc('test.xsl'))/*
  )
};
```
with test.xsl (executed by saxon 9.7 HE)
```xslt
<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns:math="http://www.w3.org/2005/xpath-functions/math"
    xmlns:xd="http://www.oxygenxml.com/ns/doc/xsl"
    xmlns="http://www.w3.org/1999/xhtml"
    exclude-result-prefixes="xs math xd"
    version="3.0">
    <xd:doc scope="stylesheet">
        <xd:desc>Some xsl that calls back into BaseX
        </xd:desc>
    </xd:doc>
    
    <xsl:template match="/">        
        <html>
            <title>Test</title>
            <body>        
                <h1>Test</h1>
                <p>Data:</p>				
		<ol>
			<xsl:for-each select="1 to 20">
				<li><xsl:value-of select="serialize(doc('http://localhost:8984/?get-data=true'))"/></li>
			</xsl:for-each>
		</ol>
            </body>
        </html>
    </xsl:template>
</xsl:stylesheet>
```
yields
```html
<html xmlns="http://www.w3.org/1999/xhtml">
   <title>Test</title>
   <body>
      <h1>Test</h1>
      <p>Data:</p>
      <ol>
         <li>&lt;test&gt;
            &lt;data&gt;Sth&lt;/data&gt;
            &lt;/test&gt;
         </li>
         [...]
         <li>&lt;test&gt;
            &lt;data&gt;Sth&lt;/data&gt;
            &lt;/test&gt;
         </li>
      </ol>
   </body>
</html>
```
Perhaps this can be made into a test case?
I hope that this does not lead to any thread related conflicts or data corruption. I don't know yet how to test for that.

**Comment by ChristianGruen** [comment] 2017-06-26 11:08
It’s true, I didn’t have enough time for test cases yesterday; something that needs to be done before the issue is closed (I hope we can add a test that requires no additional libraries).

**Comment by simar0at** [comment] 2017-06-26 12:25
In this case I really like to know that Saxon 9 HE works. I like that processor.
I tried without Saxon 9 and changing XSL to 1.0 now and using fn:document and the results are different. Now it does not lock up right away. That is much better. I get:
```
Stopped at Q:/BaseX/webapp/test.xqm, 23/17:
[bxerr:BXSL0001] ERROR:  'com.sun.org.apache.xml.internal.utils.WrappedRuntimeException: Server returned HTTP response code: 401 for URL: http://localhost:8984/?get-data=true'
```
Changing to http://admin:admin@localhost:8984/?get-data=true did not get me access
```xquery
xquery version "3.1";
module namespace api = "http://acdh.oeaw.ac.at/xslt-call/api";

import module namespace rest = "http://exquery.org/ns/restxq";
import module namespace xslt ="http://basex.org/modules/xslt";

declare
  %rest:path("")
  %rest:query-param("get-data", "{$get-data}", "false")
function api:index-file($get-data as xs:boolean) as item()+ {
  (
  <rest:response>
    <http:response status="200" message="">
      <http:header name="Content-Language" value="en"/>
      <http:header name="Content-Type" value="text/html; charset=utf-8"/>
    </http:response>
  </rest:response>,
  if ($get-data) then
  <test>
    <data>Sth</data>
  </test>
  else
  xslt:transform(<repeat>{for $i in 1 to 20 return <i/>}</repeat> , doc('test.xsl'))/*
  )
};
```
```xslt
<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns:math="http://www.w3.org/2005/xpath-functions/math"
    xmlns:xd="http://www.oxygenxml.com/ns/doc/xsl"
    xmlns="http://www.w3.org/1999/xhtml"
    exclude-result-prefixes="xs math xd"
    version="1.0">
    <xd:doc scope="stylesheet">
        <xd:desc>Some xsl that calls back into BaseX
        </xd:desc>
    </xd:doc>
     
    <xsl:template match="/">
        <html>
            <title>Test</title>
            <body>        
                <h1>Test</h1>
                <p>Data: </p>				
                    <ol>
                        <xsl:for-each select="repeat/i">
                            <li><xsl:copy-of select="document('http://localhost:8984/?get-data=true')/test/data/text()"/></li>
                         </xsl:for-each>
                     </ol>
                <p><xsl:value-of select="concat(system-property('xsl:vendor'), ': ', system-property('xsl:vendor-url'))"/></p>
            </body>
        </html>
    </xsl:template>
</xsl:stylesheet>
```
If I use Saxon 9 to interpret this XSL 1.0 then it looks like the result fetched from the server is empty. So unfortunately I can not reproduce the problem without using Saxon 9 in XSL 2.0 or 3.0 mode.
On the other hand Saxon 9 HE is a maven artifact and perhaps it is worth the effort to pull it in for some tests.
So nothing bad happens if you don't use fn:doc in XSL.

**Comment by ChristianGruen** [comment] 2017-06-26 12:38
I liked your initial example, it does not require Saxon.

But to understand your last example better.. Do you think that the proposed bug fix does not solve the problem, or only partially?

**Comment by ChristianGruen** [comment] 2017-06-26 19:06
I have added some test cases for the two extensions that I have added in the scope of this issue. I also like Saxon, but I believe it’s a good rule of thumb to write tests that are both a) as generic and b) as basic as possible.

Moreover, before we add further tests, I first need to understand what exactly fails right now. Could you possibly summarize for me again what else you believe needs to be done? If we talk about failures that exclusively occur with Saxon, it may be that this is something for the Saxon mailing list (provided that it’s possible to create a reproducible example).

**Comment by simar0at** [comment] 2017-06-27 09:44
Sorry, I did not mean to be misleading:
* The problem is solved as far as I can see. No more dead locks, BaseXes fn:doc and even the fn:doc in saxon does what I expect.
* My last post is probably not helpful und it turned out to be unrelated. I thought I could come up with some code XSL code for Xalan that also locks up exist. It does not. That fn:document in XSL 1.0 does not seem to use the same code path. I would not say it works, but it doesn't cause a dead lock.
So if you asked my the issue is solved.

**Comment by ChristianGruen** [comment] 2017-06-27 10:11
Thanks for the feedback. I’m glad to learn that the problem seems to be solved. I’ll close the issue; please feel free to reopen it if we have overlooked something.

**Closed by ChristianGruen** 2017-06-27 10:11 UTC
